name: ubuntu

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: CI
      run: make -f ubuntu.mk ci
